export const SUBMIT_DATA = "SUBMIT_DATA";
export const DELETE_SELECT_EMPLOYEE = "DELETE_SELECT_EMPLOYEE";
export const SERCH_USER_DATA = "SERCH_USER_DATA";
export const FIND_IN_LIST = "FIND_IN_LIST";
export const SELECT_EDIT_LIST = "SELECT_EDIT_LIST";
